version: '3'

services:

  service:
    container_name: combinator
    build: ./
    restart: always
    command: ["poetry", "run", "python", "main.py"]
    deploy:
      resources:
        limits:
          cpus: '0.25'
        reservations:
          cpus: '0.15'
    networks:
      - GLOBAL_NETWORK
    environment:
      INFISICAL_HOST: ${INFISICAL_HOST}
      INFISICAL_TOKEN: ${INFISICAL_TOKEN}
      ENVIRONMENT_SLUG: ${ENVIRONMENT_SLUG}

volumes:
  redis-data:

networks:
  GLOBAL_NETWORK:
    external: true